### ISSUE TITLE
grid sampling of CT detection rate and quarantine effectiveness

### ISSUE THREAD

**Issue by jgerardin** [numalariamodeling/covid-chicago#288]

**Comment by ManuelaRunge** [comment]
Issue is closely related to
[gridded CT + Q exploration at multiple levels of resuming contacts#292]( https://app.zenhub.com/workspaces/covid-19-modeling-5e8b85bb090561fddfdc48ec/issues/numalariamodeling/covid-chicago/292
)
closing this issue
