### ISSUE TITLE
LTCF simulation

### ISSUE THREAD

**Issue by jgerardin** [numalariamodeling/covid-chicago#289]
Create a simulation of transmission within a LTCF (including importation). Use EMS11 Ki and age structure to reflect workers and residents. Workers can import covid (maybe they get their own locale with some transmission?) Test various strategies such as weekly testing, daily testing, etc.

**Comment by ManuelaRunge** [comment]
Related PR's  from Natsumi on LTCF model

[](https://github.com/numalariamodeling/covid-chicago/pull/370/files)
[](https://github.com/numalariamodeling/covid-chicago/pull/367)
[](https://github.com/numalariamodeling/covid-chicago/pull/365)
