### ISSUE TITLE
bug fix: running multiple samples 

### ISSUE THREAD

**Issue by ManuelaRunge** [numalariamodeling/covid-chicago#351]
in order to run full factorial between sampling and intervention parameters, it appears that the sample parameters are set to 1 and the same samples are repeated for n as defined in  'number_of_samples': 10 - (see [changes here](https://github.com/numalariamodeling/covid-chicago/commit/c6bf91d61eaa877c7b57a798a9dc52e0c7e351a1#diff-adb51896c8313ad997cfba729282a42eR43))

**Comment by ManuelaRunge** [comment]
Hi @jacksonllee  just to follow up , is there a way we could make use of the `number_of_samples `again for the sample parameters, and remove full factorial among the sample parameters ? (keep full factorial between sample, intervention, date and Ki parameters, and full factorial among the intervention parameters as it currently is) ?

**Comment by jacksonllee** [comment]
> is there a way we could make use of the number_of_samples again for the sample parameters, and remove full factorial among the sample parameters ?

yup, I'm working on this. I'm trying to put up a pull request either today or tomorrow.

**Comment by jacksonllee** [comment]
@ManuelaRunge Question: For sampled parameters, is there a use case of drawing more than one random number for a given parameter (e.g., `time_to_infectious`)? In other words, if we want to remove full factorial among sample parameters, I would have trouble seeing how `size: 2` (so more than 1) in the following hypothetical example yaml would interact with the other parameters:

```yaml
  'time_to_infectious':
    np.random: uniform
    function_kwargs: {'low': 3.4, 'high':4.5, 'size': 3}
```

If you can confirm that we would not use something like `size: 2` in sampled parameters, then the code changes would be straightforward. Otherwise, more guidance from you would be needed.

**Comment by ManuelaRunge** [comment]
@jacksonllee 

[here ](https://github.com/numalariamodeling/covid-chicago/blob/master/experiment_configs/extendedcobey_200428.yaml#L2 )we select 50 samples , so each of the [sample parameter ](https://github.com/numalariamodeling/covid-chicago/blob/master/experiment_configs/extendedcobey_200428.yaml#L43)  

```
  'time_to_infectious':
    np.random: uniform
    function_kwargs: {'low': 3.4, 'high':4.5}
  'time_to_symptoms':
    np.random: uniform
    function_kwargs: {'low': 2.4, 'high': 3.5}
  'time_to_detection':
    np.random: uniform
    function_kwargs: {'low':2.9, 'high':2.9}
  'time_to_hospitalization':
    np.random: uniform
    function_kwargs: {'low':3, 'high':6}
  'time_to_critical':
    np.random: uniform
    function_kwargs: {'low':4, 'high':6}
  'time_to_death':
    np.random: uniform
    function_kwargs: {'low':4, 'high':6
....
```}
etc is drawn 50 times.

Before the implementation of full factorial with [intervention parameters ](https://github.com/numalariamodeling/covid-chicago/blob/master/experiment_configs/extendedcobey_200428.yaml#L101),   each sample  was repeated for each Ki and startdate and the intervention parameter were included in the 50 samples. 

So the ,` 'size': 3`  should only apply to Ki and the intervention parameters (effect sizes + time events). 
Initially I thought the loop for the Kivalues could just include the intervention parameters as well, but because of the time events it is not that straight forward. 

It seems to me that the sample_parameters and intervention_parameters [here ](https://github.com/numalariamodeling/covid-chicago/blob/master/runScenarios.py#L240)need to be separated ? 


Not sure if that is helpful, but attached a schematic in excel. 
If it is easier the sample_parameters.csv could be generated first and then used to replace parameters reading of row by row..... ? 

![Capture](https://user-images.githubusercontent.com/8237612/83575661-a2977880-a4f5-11ea-9c8c-a73b74b22079.PNG)

**Comment by ManuelaRunge** [comment]
![Capture.PNG](https://images.zenhubusercontent.com/5e8b60dce946d6297b84f856/3fefa27c-ad7f-42b5-9421-aed4de383d89)
