### ISSUE TITLE
align plot region titles in python plotters 

### ISSUE THREAD

**Issue by ManuelaRunge** [numalariamodeling/covid-chicago#535]
The scripts producing plots in [plotters](https://github.com/numalariamodeling/covid-chicago/tree/master/plotters) use different names for the regions.  `covidregion 1`,  just numbers `1-11`, `covid region`, or `region`,   these should be `COVID-19 region 1-11`. 

Example code for renaming labels 
```
plotsubtitle = ems_num.replace('EMS-', 'COVID-19 region ')
if ems_num == 'All' :
    plotsubtitle = ems_num.replace('All', 'Illinois')
ax.set_title(plotsubtitle)
```

**Comment by ArielleEagan** [comment]
My first Git assignment! I accept! haha :) I will circle back with any questions. Thank you
