### ISSUE TITLE
create B.1.1.7 model variant scenario

### ISSUE THREAD

**Issue by ManuelaRunge** [numalariamodeling/covid-chicago#623]
- with increased transmission, same severity
-  with increased transmission increased severity

**Comment by ArielleEagan** [comment]
SAGE meeting paper: "NERVTAG note on B.1.1.7 severity" here: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/955239/NERVTAG_paper_on_variant_of_concern__VOC__B.1.1.7.pdf
